services:
  api:
    image: async_api_image
    build: .
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host $SERVICE_HOST --port $SERVICE_PORT
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d auth_database" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
#      - redis
    networks:
      - default
    container_name: 'middle_practicum_api'

  postgres:
    image: postgres:16.0
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - default
    container_name: 'middle_practicum_auth_postgres'

  redis:
    image: redis:7.2.5
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
    env_file:
      - .env
    ports:
      - 6380:6379
    networks:
      - default
    container_name: 'middle_practicum_auth_redis'

#  nginx:
#    entrypoint: [ "echo", "Service nginx disabled in dev mode" ]


volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24