services:

  ### service admin panel ###
  admin_panel_postgres:
    ports:
      - "5435:5432"

  admin_panel_django:
    ports:
      - "8000:8000"

  admin_panel_nginx:
    ports:
      - "80:80"

  ### service auth ###
  auth_api:
    ports:
      - 8001:8000
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  auth_postgres:
    ports:
      - "5433:5432"

  auth_redis:
    ports:
      - 6380:6379

  auth_nginx:
    ports:
      - "81:80"


volumes:
  postgres_data:
  redis_data:
