version: '3.4'
services:

  content_api:
    ports:
      - "8002:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000


  content_redis:
    ports:
      - "6382:6379"


  content_elasticsearch:
    ports:
      - "9200:9200"


  content_nginx:
    ports:
      - "82:80"

  jaeger_service:
    ports:
      - '6831:6831/udp'
      - '16686:16686'

volumes:
  esdata01:

#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.16.57.0/24