"""empty message

Revision ID: 63adb549cc1d
Revises: dfef77c26d2f
Create Date: 2024-06-21 10:49:47.803979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63adb549cc1d'
down_revision: Union[str, None] = 'dfef77c26d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'user_login_history', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_login_history', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
